### PR TITLE
update jquery to ~1.10 in bower.json

### PR DESCRIPTION
**Pull request by metalmatze**
Updating jquery to version ~1.10.
The ~ says it should be around 1.10.
Maybe 1.10.1 or the current 1.10.2 or in the future 1.10.3

### CODE REVIEW

**Comment by rtablada** [comment]
Not sure on this one. @ericbarnes is there reasoning behind 1.9 vs 1.10?

**Comment by ericlbarnes** [comment]
Yeah it appears http://marionettejs.com/ states 1.9 but not any higher. I have honestly not tried that with 1.10+ but I will try and research it.

**Comment by rtablada** [comment]
Cool, I thought there may have been some reasoning behind the magic.

**Comment by ericlbarnes** [comment]
Confirmed marionette will indeed work with this version. Thanks!

**Comment by ericlbarnes** [comment]
Also just as an FYI I have the jquery pulled via cdn currently but plan on implementing this better in the future.

**Comment by metalmatze** [comment]
:+1:

**Pull request merged**
