### PR TITLE
Retrieve latest posts without offsets

### PR DESCRIPTION
**Pull request by koomai**
The current method Wardrobe::posts() retrieves the latest posts but paginates them.

http://paste.laravel.com/Sfx

This new method retrieves the latest X posts so that you can do things like display a list of latest articles on the sidebar.

### CODE REVIEW

**Comment by ericlbarnes** [comment]
The facadeSearch you deleted does exactly this but with more options allowing you to pass in search params. Not sure I'm following the logic here?

**Comment by koomai** [comment]
Hey Eric,

Sorry - a) didn't realise this method had been added recently  b) screwed up by writing over the new file so it looks like I deleted the new method.

Cheers!

**Comment by koomai** [comment]
It was a composer caching issue - still installs v1.0.0

**Comment by ericlbarnes** [comment]
This was a recent change for v1.1 so I think it would require using dev master.

**Comment by koomai** [comment]
Yeah - just did that. All good now :) Thanks.

**Pull request closed without merging**
