### PR TITLE
Re-added support for theme-specific routes

### PR DESCRIPTION
**Pull request by adamwathan**
- Moved theme-view setup into service provider and out of BaseController (theme routes could not render views otherwise)
- Included theme-specific routes in routes file

### CODE REVIEW

**Comment by rtablada** [comment]
Not sure about moving the view setup out of the base controller. I put it there to avoid view naming conflicts since it would only be loaded on Wardrobe routes.

May look at offering a helper within the facade...

@ericbarnes what's your thoughts on it?

**Comment by adamwathan** [comment]
Ah I didn't realize there might be side affects to moving the setup. Can
you give an example of where you might run into a naming conflict?

Any other solutions that make the views available in the theme routes files
are great too, this is just what came to mind first and seemed to work
without any issues on the small project I was testing it with.

On 2013-08-18, at 1:33 PM, Ryan Tablada notifications@github.com wrote:

Not sure about moving the view setup out of the base controller. I put it
there to avoid view naming conflicts since it would only be loaded on
Wardrobe routes.

May look at offering a helper within the facade...

@ericbarnes https://github.com/ericbarnes what's your thoughts on it?

—
Reply to this email directly or view it on
GitHubhttps://github.com/wardrobecms/core/pull/20#issuecomment-22835035
.

**Comment by adamwathan** [comment]
Actually I get what you're saying now, you might have views in the regular
views folder that clash if you are using Wardrobe as just part of a bigger
page...

On 2013-08-18, at 1:33 PM, Ryan Tablada notifications@github.com wrote:

Not sure about moving the view setup out of the base controller. I put it
there to avoid view naming conflicts since it would only be loaded on
Wardrobe routes.

May look at offering a helper within the facade...

@ericbarnes https://github.com/ericbarnes what's your thoughts on it?

—
Reply to this email directly or view it on
GitHubhttps://github.com/wardrobecms/core/pull/20#issuecomment-22835035
.

**Comment by rtablada** [comment]
Yeah, I have Wardrobe on a current site where my theme is 'Marketing' and then my marketing front facing site has a 'Marketing' namespace and this would create issues for the `index` view on the regular marketing site.

**Comment by adamwathan** [comment]
Ah crap I didn't realize that any other commits I made to that branch on my own fork would become part of this pull request... Forgive my n00bness to actually trying to contribute on Github, usually just a leech ;) I'll split them up, I never actually intended to submit the PR involving the Markdown parser but can do if you guys think it's a good idea.

**Comment by adamwathan** [comment]
Regarding the naming conflicts, the first solution that comes to mind is maybe to namespace all of the Wardrobe theme views under a parent "theme" or "wardrobe" or something namespace?

**Comment by rtablada** [comment]
Not sure about that, let me go down the route of adding a `Wardrobe::setupThemes()` function.

**Comment by adamwathan** [comment]
Sounds good, I'll hold off on resubmitting this one without the other mixed in commit then!

**Comment by Chumper** [comment]
Did you test the function? I get the error 'theme'.'page' not found.
I use the theem_view but that does not work.

**Comment by adamwathan** [comment]
As long as you call Wardrobe::setupViews() in your (theme)/route.php file before doing any View::make() stuff it should work. Working here at least?

**Comment by rtablada** [comment]
I would suggest calling it within your route itself in order to minimize namespace leaking.

**Comment by Chumper** [comment]
ok, perfect, may i haven't looked close enough...

**Pull request closed without merging**
